services:
  api:
    restart: unless-stopped
    env_file: "./docker/.env"
    build:
      context: ./api
      dockerfile: ../docker/api.Dockerfile
    ports:
      - 3000:3000
    develop:
      watch:
        - path: api/package.json
          action: rebuild
        - path: api/yarn.lock
          action: rebuild
        - path: api/
          ignore:
            - node_modules/
          target: /app
          action: sync

  front:
    restart: unless-stopped
    env_file: "./docker/.env"
    build:
      context: ./front
      dockerfile: ../docker/front.Dockerfile
    ports:
      - 5173:5173
    develop:
      watch:
        - path: front/package.json
          action: rebuild
        - path: front/yarn.lock
          action: rebuild
        - path: front/
          ignore:
            - node_modules/
          target: /app
          action: sync
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: "./docker/.env"
